name: Java CI with Maven Build AEM repository

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Running jobs directly on the runner machine
  aem:
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: maven

      - name: Set up our custom Artifactory instance
        uses: actions/setup-java@v2
        with: # running setup-java again overwrites the settings.xml
          java-version: 11
          distribution: 'adopt'
          cache: maven
          server-id: artifactory
          server-username: AEM_CLOUD_ARTIFACTORY_USER
          server-password: AEM_CLOUD_ARTIFACTORY_API_KEY

      - name: Build project
        run: mvn -e -s $GITHUB_WORKSPACE/.m2/settings.xml clean package
        working-directory: ./eventhub-api-webapp
        env:
          AEM_CLOUD_ARTIFACTORY_USER: ${{ secrets.AEM_CLOUD_ARTIFACTORY_USER }}
          AEM_CLOUD_ARTIFACTORY_API_KEY: ${{ secrets.AEM_CLOUD_ARTIFACTORY_API_KEY }}

